image: Visual Studio 2019

branches:
  except:
  - maintenance/1.x

environment:
  SHFBROOT:  C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  SandCastleZipFile: SHFBInstaller.zip
  SandCastleUri: https://github.com/EWSoftware/SHFB/releases/download/v2019.11.17.0/SHFBInstaller_v2019.11.17.0.zip
  
install:
  - choco install gitversion.portable -pre -y
  - ps: Start-FileDownload $env:SandCastleUri -FileName $env:SandCastleZipFile
  - cmd: 7z x SHFBInstaller.zip -y
  - ps: msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet /qn /norestart /log install.log

before_build:
  - ps: gitversion /l console /output buildserver /updateassemblyinfo
  - ps: dotnet restore dotNetRDF.sln

configuration: Release

build_script:
  - ps: dotnet build dotNetRDF.sln --configuration=Release
  - ps: dotnet pack -o $env:APPVEYOR_BUILD_FOLDER\nugets --no-build --configuration Release -p:Version=$env:GitVersion_NuGetVersion
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { msbuild Build\shfb\dotnetrdf.shfbproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:HelpFileVersion=$env:GitVersion_NuGetVersion }

test_script:
  - ps: dotnet test -c Release --filter "Category!=explicit" --framework netcoreapp3.1 Testing\unittest\unittest.csproj
  - ps: dotnet test -c Release --filter "Category!=explicit" --framework net472 Testing\unittest\unittest.csproj
  - ps: dotnet test -c Release --filter "Category=fulltext" --framework net472

deploy:
  - provider: GitHub
    description: 'dotNetRDF $(GitVersion_SemVer)'
    auth_token:
      secure: j3GoyDavErTD91EcSTfNBbQyTc7tqpp+klmmz85xC4fjbE8Gl2brFjr8t3/Zzwmk
    on:
      appveyor_repo_tag: true 
    artifact: Build\shfb\Help.zip, Build\shfb\Help\dotNetRDFApi.chm, /.*\.nupkg/
  - provider: NuGet
    api_key:
      secure: 9zViqGPPKYiYVnk9iH14649Oj6tXTwsNxtZ73AcsESYm795D918U0D3UlH9zjxcT
    on:
      appveyor_repo_tag: true
    artifact: /((?!Spin).)*.nupkg/

artifacts:
  - path: nugets\*.nupkg
  - path: Build\shfb\Help\dotNetRDFApi.chm
  - path: Build\shfb\Help

