#
# Makefile pelda a string1 feladat (3. labor) megoldasanak forditasara 
# gnumake valtozat
# 	Linuxokon es ural2-n is elerheto
#
# A make paranccsorabol magadott CMD valtozo tartalma atadodik a forditonak
# Pl:
# make -CMD=-DMEMTRACE
#
PROG = main   # a program neve (ezt allitjuk elo)
PROG_O = main.o alakzat.o kor.o szakasz.o szin.o pont.o  # program object fajljai 
PROG_H = alakzat.h kor.h szakasz.h szin.h pont.h  # program header fajljai
PROG_L =              # program libjei

MTRACE_O = memtrace.o # memtrace object fajl
MTRACE_H = memtrace.h # memtrace header fajlja
MEMCHK_L = -lmalloc   # ural2-n a memcheck-hez kell. linuxon kikommentezendo

CXX = g++   # a C fordito neve
#CXX = clang++ # clang-ot (llvm) is erdemes kiprobalni
CXXFLAGS = -pedantic -Wall # kapcsolok: legyen bobeszedu es pedans
CXXFLAGS += -g # es legyeb debug info is
CXXFLAGS += $(CMD) # es amit a parancsorbol megadnak
LDFLAGS = -g # debug a linkelesnel 

# osszes object, osszes header osszes lib
OBJS = $(PROG_O) $(MTRACE_O)
HEADS = $(PROG_H) $(MTRACE_H)
LIBS = $(PROG_L) $(MEMCHK_L)

# alapertelmezett cel: program
.PHONY: all
all: $(PROG)

$(PROG): $(OBJS)
	$(CXX) $(LDFLAGS) $(OBJS) -o $@ $(LIBS)

# feltetelezzuk, hogy az osszes obj fugg az osszes headertol, ami nem feltetlenul igaz
$(OBJS): $(HEADS)

# takaritas igeny szerint
.PHONY: clean
clean:
	rm -f $(OBJS) $(PROG)

