import java.io.FileNotFoundException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Application.java
//  @ Date : 22/10/2019
//  @ Author : 
//
//




public class Application {
	public static void main(String[] args) throws FileNotFoundException 
	{
		PercentCounter pc = new PercentCounter();
		pc.register(new StdOutLogger());
		pc.register(new FileLogger("observer.txt"));
		pc.run();

	}
}
