import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FileLogger.java
//  @ Date : 22/10/2019
//  @ Author : 
//
//




public class FileLogger extends Observer 
{
	PrintWriter f;
	public FileLogger(String fileName) throws FileNotFoundException 
	{
		f=new PrintWriter(new FileOutputStream(fileName));
	}

	public void report(Observable observable) 
	{
		f.println(observable);
		f.flush();
	}
	
	public void finalize()
	{
		f.close();
	}

}
