import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observable.java
//  @ Date : 22/10/2019
//  @ Author : 
//
//




public class Observable {
	
	private List<Observer> observers = new ArrayList<Observer>();
	
	public void register(Observer observer) 
	{
		observers.add(observer);
	}
	
	public void unregister(Observer observer) 
	{
		observers.remove(observer);
	}
	
	public void reportToObservers() 
	{
		for(Observer x: observers)
			x.report(this);
	}

}
