//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StdOutLogger.java
//  @ Date : 22/10/2019
//  @ Author : 
//
//




public class StdOutLogger extends Observer 
{
	public void report(Observable observable)
	{
		System.out.println(observable);
	}
}
